apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "admitik.fullname" . }}-manager
  labels:
    {{- include "admitik.labels" . | nindent 4 }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies/status
  verbs:
  - get
  - patch
  - update


