# permissions for end users to edit admissionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: admitik
    app.kubernetes.io/managed-by: kustomize
  name: admissionpolicy-editor-role
rules:
- apiGroups:
  - admitik.freepik.com
  resources:
  - admissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.freepik.com
  resources:
  - admissionpolicies/status
  verbs:
  - get
