---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - admitik.freepik.com
  resources:
  - clusteradmissionpolicies/status
  verbs:
  - get
  - patch
  - update
