apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "admitik.fullname" . }}-leader-election
  labels:
    {{- include "admitik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "admitik.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "admitik.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
